FROM node:22-alpine3.22 AS builder
WORKDIR /usr/src/app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build

FROM node:22-alpine3.22
WORKDIR /usr/src/app
COPY package*.json ./
RUN npm install --production
COPY --from=builder /usr/src/app/dist ./dist
COPY prisma ./prisma

EXPOSE ${PORT}
CMD ["sh", "-c", "npm run db:deploy && npm run start:prod"]
