version: '3.8'

services:
  db:
    container_name: postgress-db
    build: 
      context: ./database
      dockerfile: Dockerfile
    restart: always
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - library-network

  app:
    container_name: nestjs-app
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    restart: always
    ports:
      - ${PORT}:${PORT}
    env_file:
      - .env
    networks:
      - library-network
    command: npm run start:dev

volumes:
  postgres_data:
    driver: local

networks:
  library-network:
    driver: bridge
